### ISSUE TITLE
unused argument (scales = 2)

### ISSUE THREAD

**Issue by dawnmy** [YuLab-SMU/ggbreak#15]
When using scales to specify the height ratio of the subplots, I got this error

```shell
Error in scale_y_break(breaks = c(500, 10000), scales = 2) : 
  unused argument (scales = 2)
```
I am using ggbreak v0.0.3, ggplot2 v3.3.5, R v4.0.0 on macOS 11.4.

**Comment by GuangchuangYu** [comment]
the current version is 0.0.7.
