### ISSUE TITLE
Set scale limits

### ISSUE THREAD

**Issue by iferres** [YuLab-SMU/ggbreak#22]
Hi, I was wondering if it is possible to set axis limits . For instance:
```r
library(ggplot2)
library(ggbreak)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point() + 
  xlim(c(0, 10)) + 
  scale_x_break(c(2, 3))  
```
The above example ignores the limits set by `xlim()`.

Very helpful package, btw. Thanks!

**Comment by GuangchuangYu** [comment]
```
+ expand_limits(x=c(0, 10))
```

should works

**Comment by iferres** [comment]
Yep, that did the trick.
Thanks!

**Comment by GuangchuangYu** [comment]
fixed by <https://github.com/YuLab-SMU/ggbreak/pull/29>, now it works fine with `xlim` and `ylim`.
