### ISSUE TITLE
Font of axis titles incorrectly displayed

### ISSUE THREAD

**Issue by lglip** [YuLab-SMU/ggbreak#24]
I stumbled upon an issue with the font of the axis titles. It automatically reverts to the standard font, no matter which formatting rules I try to apply (e.g., text, axis.title, title, xlab(), ylab()). See the snippet below for a reprex.

```
library(magrittr)
library(ggplot2)
library(ggbreak)
data("cars")

cars %>% ggplot(aes(x = speed)) +
  geom_bar() +
  scale_y_break(c(2,3)) +
  theme(text = element_text(family = "Comic Sans MS"))
```

P.S. Of course I do not want to use Comic Sans MS :-) but if you run this example it becomes clear that the axis titles are definitely **not** displayed in this font, while the values along the axes are.

**Comment by GuangchuangYu** [comment]
@xiangpin pls confirm whether it was fixed by <https://github.com/YuLab-SMU/ggbreak/pull/23>.
