### ISSUE TITLE
scale_wrap() function.

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/ggbreak#3]
~~scale_wrap function~~

```r
ggplot(economics, aes(x = ggtree::Date2decimal(date), y = unemploy, colour = uempmed)) +
  geom_line() -> p

scale_wrap <- function(n) {

}

p + scale_wrap(4)
```

The `scale_wrap` function is expected to break down a long (horizontal) figure to several pieces.

![image](https://user-images.githubusercontent.com/626539/117752469-644c2280-b249-11eb-8461-ae832d9eacb2.png)

prototyping here:

```r
rr = ggbreak:::ggrange2(p, 'x')$axis_range
seq(rr[1], rr[2],length.out= 5)->xx
lapply(seq_len(length(xx)-1), function(i) p + coord_cartesian(xlim=c(xx[i], xx[i+1])) + xlab(NULL) + ylab(NULL)
) -> gg
aplot::plot_list(gg, ncol=1) + plot_layout(guides="collect") -> pg
ggbreak:::set_axis_label(as.ggplot(pg), p$label$x, p$label$y, p) 
```

~~1. `ggplotify` v 0.0.7 will compatible with patchwork and you can transfer using cowplot to patchwork for easy to collect legends.~~
2. maybe we need to support date object. Currently we need to convert to decimal in this example with `ggtree::Date2decimal(date)`.

**Comment by GuangchuangYu** [comment]
@xiangpin  date object is currently supported with `scale_wrap`, see <https://github.com/YuLab-SMU/ggbreak/commit/ea2d2336fb28d13d9b60599a9b40d0c7e9cefee7>.

pls update other scale function accordingly to support it. and maybe test it with combination of other scale functions, e.g. date axis + reverse scale.

**Comment by xiangpin** [comment]
I think it is better to use `transform` of the internal function of `scale`. We can compatible other scale functions, e.g scale_XX_log10, scale_XX_date, scale_XX_sqrt, scale_XX_time. We can extract the function using the following code.

```
transfun <- ggplot_built(p)$layout$panel_scale_x[[1]]$trans$transform
```

And I test the example with combination of scale_x_reverse, and other scale. It generated error, because it is not compatible between the different `trans` function.

**Comment by GuangchuangYu** [comment]
ggplot2 only allow one scale function to transfrom the data and we should follow this strategy.

However, as you supported scale_x_break with scale_x_reverse, I believe it should be worked also for date instead of numeric x axis. Date is actually a special numeric value.
