### ISSUE TITLE
Incompatible with ggarrange and grid.arrange?

### ISSUE THREAD

**Issue by NataliHB** [YuLab-SMU/ggbreak#36]
Hi,

thank you for this very useful package, I was wondering if ggbreak is compatible with ggarrange and grid.arrange?

When I plot the graphs individually it works like a charm but when I try to put them together in a panel the breaks are not maintained, a fix for that will be very helpful.

Cheers,
Natali

**Comment by xiangpin** [comment]
Please add `print` for the object generated by `scale_` functions of `ggbreak` if using `grid.arrange`.

```
library(ggbreak)
library(ggplot2)
set.seed(2019-01-19)
d <- data.frame(
            x = 1:20,
            y = c(rnorm(5) + 4, rnorm(5) + 20, rnorm(5) + 5, rnorm(5) + 22)
        )
p <- ggplot(d, aes(x, y)) + geom_col()
x1 <- p+scale_y_break(c(7, 17 ))
library(gridExtra)
grid.arrange(print(x1), print(x1), ncol=2)
```
![xx](https://user-images.githubusercontent.com/17870644/146705334-026915f0-7e09-4d51-aaff-b12bc2bd050e.PNG)

Or you can use `plot_list` of `aplot` to do this. You can refer to [this](https://github.com/YuLab-SMU/ggbreak/issues/32#issuecomment-976151910).

**Comment by NataliHB** [comment]
Many thanks, it worked perfectly!

**Comment by n-dempe** [comment]
Sorry but I can't use common.legend = TRUE anymore
after using print(). Do you know why?

e.g.: 
ggarrange(print(A), print(A), print(A), print(A), print(A), print(A), 
          ncol = 3, nrow = 2, common.legend = TRUE)

**Comment by GuangchuangYu** [comment]
maybe you can try `aplot::plot_list()`.

**Comment by n-dempe** [comment]
Thanks for the advice!
