### ISSUE TITLE
Dual axis

### ISSUE THREAD

**Issue by SaltyRydM** [YuLab-SMU/ggbreak#48]
Hi,
There seem to be an issue using ggbreak when working with dual axis plot. It works fine if you want to do the cut/break across the axis where you have the dual axis, but if you do the break along with the dual-axis you end up with axis labels and ticks in the wrong position (See below).

![Rplot02](https://user-images.githubusercontent.com/65944393/168295811-b090f91e-b659-4fa2-9e56-7922e77ef339.png)
)

As you can see in this example using scale_x_cut(), the secondary y-axis is placed wrong and the sec.axis name is placed twice. 

The same thing also happens if you try to do it in the example shown in Feature 11, changing scale_y_break to scale_x_break: 
https://cran.r-project.org/web/packages/ggbreak/vignettes/ggbreak.html

Hope this issue is easily solved!

M

**Comment by GuangchuangYu** [comment]
fixed in v > 0.1.0, see <https://cran.r-project.org/web/packages/ggbreak>.

**Comment by SaltyRydM** [comment]
It now works! Thank you so much for rapidly fixing this issue!
