### ISSUE TITLE
A dual y-axis added 

### ISSUE THREAD

**Issue by jolehtonen** [YuLab-SMU/ggbreak#51]
Hi, I would like to use ggbreak in my plots but it draws a dual y-axis to my plots. Is there still a bug in the package? Any help is appreciated. 

  scale_y_continuous(breaks=seq(0, 60000, 10000)) +
  scale_y_break(c(20000, 50000))

![Untitled-2](https://user-images.githubusercontent.com/111284832/184851138-a4ac3d41-e9c1-4666-9628-32ef08cf5a2f.png)

**Comment by ZJURenyi** [comment]
Found the same issue. I tried removing ylim and the second y axis was gone. I guess you might need to delete scale_y_continuous

**Comment by ClaudiuPapasteri** [comment]
I also encountered this. Using any limits (lime `ylim()` or `scale_y_continuous`) will create this unwanted double axis. Can't imagine this being an wanted feature.

**Comment by bpovahppeng** [comment]
The extra text/ticks can be removed by manually setting those elements to be blank in a theme:
`theme(axis.text.y.right = element_blank(), axis.ticks.y.right = element_blank())`

**Comment by jolehtonen** [comment]
Removing scale_y_continuous didn't help. 

But thank you bpovahppeng! With your help, I managed to remove now the dual y-axis! In addition to text and ticks also the line needed to be removed. So whoever struggles with this later – this should work: 

theme(axis.text.y.right = element_blank(), axis.ticks.y.right = element_blank(), axis.line.y.right = element_blank())
