### ISSUE TITLE
Broken axis disappear when using ggarrange() to join multiple plots

### ISSUE THREAD

**Issue by npasqualotto** [YuLab-SMU/ggbreak#62]
When I am using scale_y_break() to set a gap and it works perfectly. However, the gap disappear when I try to join two plots into a single one with garrange() function from pack ggpubr package.

I am using package version 0.1.2.

Would you have any guess on how to solve this issue? 

I would deeply appreciate it.

Best,

Nielson Pasqualotto.

Example with iris dataset:

```
library(ggplot2)
library(ggbreak)
library(ggpubr)

p1 <- ggplot() + geom_point(data=iris, aes(x=Sepal.Length, y=Petal.Width))
p1 + scale_y_break(breaks=c(0.3, 1), scale = 1.2)

p2 <- ggplot() + geom_point(data=iris, aes(x=Sepal.Width, y=Petal.Length))
p2 + scale_y_break(breaks=c(2, 3), scale = 1.2)

ggarrange(p1, p2)
```

**Comment by GuangchuangYu** [comment]
please use `aplot` to create composite plot.

**Comment by joybaker1** [comment]
I actually have similar questions and I tried to generate a list of plots with breaks and arrange it myself. But the breaks disappear in aplot::plot_list, cowplot::plot_grid, patchwork:wrap_plots and gridExtra::grid.arrange. Anyone have solutions how to work with ggbreak() for a combinned individual plots?
