### ISSUE TITLE
scale_x_cut and scale_y_cut

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/ggbreak#7]
e.g. scale_x_cut(breaks = xxx, which = i, scales = 1.2) 

the xxx specify the points to cut the x axis into pieces, if length(xxx) is 1, cut the axis into 2 pieces, if 2 cut the axis into 3 parts.

then align them in original orientation. The `which` specify which slice(s) to zoom in or out using corresponding `scales`. The position of `which` count from left to right for `scale_x_cut` and from top to bottom for `scale_y_cut`.

These two scale functions are designed to zoom in or zoom out specific regions of the plot. 

For example, in volcano plot, we can zoom in the region with abs(logFC) > 2 to have more space to label DE genes.

**Comment by xiangpin** [comment]
Ok, I got it.
