### ISSUE TITLE
doesn't play nicely with cowplot::plot_grid or ggpubr::ggarrange

### ISSUE THREAD

**Issue by AMChalkie** [YuLab-SMU/ggbreak#70]
See 

https://github.com/kassambara/ggpubr/issues/601

Expected behavior
p1.test.with.breaks looks the same in the ggarrange (and plot_grid).

Actual behavior
Plot doesn't contain brreaks.

Steps to reproduce the problem
library(ggplot2)
library(ggpubr)
library(ggbreak) 
library(cowplot) 

set.seed(2)
x<-rnorm(25)
y<-rnorm(25)
df<-data.frame(x,y)

p1.test <- ggplot(df,aes(x,y)) +  geom_point()
p1.test.with.breaks <- ggplot(df,aes(x,y)) +  geom_point() + scale_x_break(breaks=seq(-3,2,0.5))
ggpubr::ggarrange(p1.test,p1.test.with.breaks)
cowplot::plot_grid(p1.test,p1.test.with.breaks)

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/ggbreak/issues/36>
